"""empty message

Revision ID: 719cbfdce3d5
Revises: 2c4220afb1d8
Create Date: 2023-09-14 13:55:11.521025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719cbfdce3d5'
down_revision = '2c4220afb1d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
